# Generated by Django 5.1.3 on 2024-11-23 06:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Equipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('equipment_type', models.CharField(choices=[('GNSS', 'GNSS'), ('Total Station', 'Total Station'), ('Level Instrument', 'Level Instrument'), ('Drone', 'Drone')], max_length=30)),
                ('status', models.CharField(choices=[('In Store', 'In Store'), ('In Field', 'In Field')], default='In Store', max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Surveyor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('department', models.CharField(max_length=80)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Equipment_Request',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_date', models.DateField(auto_now_add=True)),
                ('status', models.CharField(choices=[('Requested', 'Requested'), ('In Field', 'In Field')], default='Requested', max_length=10)),
                ('equipment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Equipments.equipment')),
                ('surveyor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Equipments.surveyor')),
            ],
        ),
    ]
