# Generated by Django 5.1.3 on 2024-11-23 08:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Equipments', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipment_request',
            name='surveyor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Equipments.surveyor'),
        ),
    ]
